export enum SectionEnum {
  Categories,
  CategoryType,
  CategoryByType,
  NewCategories,
  MostPopularCategories,
  RecipeByCategory,
  Articles,
  MainHeaderBanners,
  Tags,
  ArticleCategory,
  AllRecipes,
  Types,
  Featured,
  MostDemanded,
  InstagramFooter,
  Instagram,
}
